# DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    ##数据初始化设置
    #进行该配置后，每次启动程序，程序都会运行resources/db/schema.sql文件，对数据库的结构进行操作。
    schema: classpath:db/schema-h2.sql
    #进行该配置后，每次启动程序，程序都会运行resources/db/data.sql文件，对数据库的数据操作。
    data: classpath:db/data-h2.sql
    url: jdbc:h2:mem:test
    username: root
    password: test

  #    schema: classpath:db/schema.sql
  #    data: classpath:db/data.sql
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    #启用SQL语句的日志记录
    show-sql: true
  h2:
    console:
      #进行该配置，你就可以通过YOUR_URL/h2访问h2 web consloe。YOUR_URL是你程序的访问URl。
      path: /h2-console
      #进行该配置，程序开启时就会启动h2 web consloe。当然这是默认的，如果你不想在启动程序时启动h2 web consloe，那么就设置为false。
      enabled: true
#
## DataSource Config
#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    schema: classpath:db/schema-h2.sql
#    data: classpath:db/data-h2.sql
#    url: jdbc:h2:mem:test
#    username: root
#    password: test
#
# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug